Post http://localhost:3000/api/v1/article
Content-Type: application/json
Accept:      application/json

    
{
    "libelle":"Lait",
    "prix": 3000,
    "quantiteStock": 20
}
###
GET http://localhost:3000/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJiYXJyb0BtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyNDY4MTE2NCwiZXhwIjoxNzI0Njg0NzY0fQ.hB48vc6ZNSKNVF6_XRIZSQlv1as0nfm31MRGS_F4UZ8


###
GET http://localhost:3000/api/v1/article/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJiYXJyb0BtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyNDY4MTE2NCwiZXhwIjoxNzI0Njg0NzY0fQ.hB48vc6ZNSKNVF6_XRIZSQlv1as0nfm31MRGS_F4UZ8




