POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json
Accept: application/json


{
    "email":"barro@ample.com",
    "password":"passer123",
    "clientId":13
}
#####

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email":"barro@mple.com",
    "password":"barro123"
}