POST http://localhost:3000/api/v1/clients
Content-Type: application/json
Accept: application/json

{
  "nom": "Barro",
  "prenom": "aruy",
  "telephone": "100191189"
}
###

GET  http://localhost:3000/api/v1/clients
  




##
Post http://localhost:3001/api/v1/clients
Accept:  application/json

{
  "nom": "John",
  "prenom": "Doe",
  "telephone": "123456789",
  "user": {
    "email": "joh@example.com",
    "password": "password123"
  }
}