POST http://localhost:3000/api/v1/dette
Content-Type: application/json
Accept: application/json

{
    "clientId": 1,
    "detail": [
        {
            "articleId": 1,
            "qteVente": 1
        },
        {
            "articleId": 2,
            "qteVente": 2
        }
    ]
}


###
GET http://localhost:3000/api/v1/dette

